input = input('Digite algo: ')

print('Input é um Alfanúmerico? Resposta: {}'.format(input.isalnum()))
print('Input é Alfabético? Resposta: {}'.format(input.isalpha()))
print('Input é um ASCII? Resposta: {}'.format(input.isascii()))
print('Input é um Digito? Resposta: {}'.format(input.isdigit()))
print('Input é um Número? Resposta: {}'.format(input.isalnum()))
print('Input é um todo Minusculo? Resposta: {}'.format(input.islower()))
print('Input é um Decimal? Resposta: {}'.format(input.isdecimal()))
print('Input é um Id? Resposta: {}'.format(input.isidentifier()))
print('Input pode ser Impresso? Resposta: {}'.format(input.isprintable()))
print('Input é um Espaço? Resposta: {}'.format(input.isspace()))
print('Input é um Titulo? Resposta: {}'.format(input.istitle()))
print('Input é um todo Maiusculo? Resposta: {}'.format(input.isupper()))